config/routes.rb
Surfalert::Application.routes.draw do
  resources :surf_preferences
  resources :users
  
  get "login" => 'login#index'
  post "login" => 'login#create'
  get "logout" => 'login#destroy'
  
  root :to => redirect("/login")
end

app/models/surf_preference.rb
class SurfPreference < ActiveRecord::Base
  attr_accessible :max_size, :min_size, :min_shape, :spot_id, :user,
                  :start_time, :end_time

  belongs_to :user
  
  validates_presence_of :max_size, :min_size, :min_shape, :spot_id,
                        :start_time, :end_time
  validates :max_size, :numericality => {
    :only_integer => true,
    :greater_than => 0,
    :less_than => 100
  }
  validates :min_size, :numericality => {
    :only_integer => true,
    :greater_than_or_equal_to => 0,
    :less_than => 100
  }
  validates :spot_id, :numericality => {:only_integer => true}
  
  # NOTE: the order of the hash determines how shapes are compared to one another.
  # the first shape should be the lowest, and the last shape should be the highest
  # (or best).
  SHAPES = {
    "p" => "Poor",
    "pf" => "Poor-Fair",
    "f" => "Fair",
    "fg" => "Fair-Good",
    "g" => "Good"
  }.freeze
  
  SPOTS = {
    113 => "Fort Point",
    114 => "North Ocean Beach",
    117 => "South Ocean Beach"
  }.freeze

  # determines if the shape is good enough according to the `min_shape` value in this preference.
  def shape_good_enough?(actual_shape_symbol)
    ordered_shapes = SHAPES.keys
    actual_index = ordered_shapes.index(actual_shape_symbol)
    desired_index = ordered_shapes.index(min_shape)
    raise "Unexpected results: #{actual_shape_symbol} : #{min_shape}" if actual_index.nil? or desired_index.nil?
    return actual_index >= desired_index
  end

  def check_surf_conditions(surf_json)
    surf_min_size = surf_json["minSize"]
    surf_max_size = surf_json["maxSize"]
    current_time = Time.now.strftime("%H%M").to_i
    start_i = start_time.strftime("%H%M").to_i
    end_i = end_time.strftime("%H%M").to_i

    Rails.logger.debug surf_min_size.to_s + " > " + min_size.to_s
    Rails.logger.debug surf_max_size.to_s + " < " + max_size.to_s
    Rails.logger.debug shape_good_enough?(surf_json["avgShape"]).to_s
    Rails.logger.debug (current_time >= start_i).to_s
    Rails.logger.debug (current_time <= end_i).to_s

    if surf_min_size >= min_size and 
       surf_max_size <= max_size and
       shape_good_enough?(surf_json["avgShape"]) and
       current_time >= start_i and
       current_time <= end_i

      msg = "Surf size is " + surf_min_size.to_s + "' to " + surf_max_size.to_s + "'"
      return true, msg
    else
      msg = "Conditions could be better... Size of surf: " +
            surf_min_size.to_s + "' to " + surf_max_size.to_s + "'"
      return false, msg
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :phone_no, :password, :password_confirmation, :surf_preferences

  has_many :surf_preferences

  validates_presence_of :email, :phone_no
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :setup_current_user
  
  attr_reader :current_user
  helper_method :current_user, :user_logged_in?
  
  def user_logged_in?
    ! @current_user.nil?
  end
  
  protected
  
    # sets up the `current_user` variable from the session.
    def setup_current_user
      @current_user = User.find(session[:user_id]) unless session[:user_id].nil?
    end
    
    # Redirects a user to the login path if they aren't logged in.
    def requires_login
      unless user_logged_in?
        return redirect_to login_index_path, notice: "You must login to view that page."
      end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_filter :requires_login, :only => [:destroy]
  
  def create
    user = User.find_by_email(params[:email])  
    if user && user.authenticate(params[:password])  
      session[:user_id] = user.id
      redirect_to surf_preferences_path
    else  
      flash[:notice] = "Invalid email or password"  
      render "index"  
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/surf_preferences_controller.rb
class SurfPreferencesController < ApplicationController
  before_filter :requires_login
  
  def index
    @surf_preferences = current_user.surf_preferences
  end
  
  def new
    @surf_preference = SurfPreference.new
  end
  
  def create
    @surf_preference = SurfPreference.new(params[:surf_preference])
    @surf_preference.user = current_user
    if @surf_preference.save
      flash[:notice] = "Your preferences have been created."
      redirect_to surf_preferences_path
    else
      render "new"
    end
  end
  
  def edit
    @surf_preference = SurfPreference.find(params[:id])
  end
  
  def update
    @surf_preference = SurfPreference.find(params[:id])
    if @surf_preference.update_attributes(params[:surf_preference])
      flash[:notice] = "Your preferences have been saved."
      redirect_to surf_preferences_path
    else
      render "edit"
    end
  end
  
  def destroy
    @surf_preference = SurfPreference.find(params[:id])
    @surf_preference.destroy
    flash[:notice] = "Your preference has been deleted."
    redirect_to surf_preferences_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new(params[:user])
  end
 
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully signed up!"
      redirect_to surf_preferences_path
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_msg(msg)
    "<div class='alert alert-success'>#{msg}</div>".html_safe
  end
  
  def alert_msg(msg)
    "<div class='alert'>#{msg}</div>".html_safe
  end
end

app/helpers/surf_preferences_helper.rb
module SurfPreferencesHelper
  def shape_selector_options(selected)
    return selector_options_helper(SurfPreference::SHAPES, selected)
  end
  
  def spot_selector_options(selected)
    return selector_options_helper(SurfPreference::SPOTS, selected)
  end
  
  private
  
    def selector_options_helper(values, selected)
      options = []
      values.each do |symbol, label|
        if symbol == selected
          s = " selected"
        else
          s = ""
        end
        options.push("<option value='#{symbol}' #{s}>#{label}</option>")
      end
      return options.join(" ")
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Surfalert</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Get a phone call when the surf is good.">
  
  <meta property="og:title" content="Surfalert" />
  <meta property="og:site_name" content="Surfalert" />
  <meta property="og:description" content="et a phone call when the surf is good." />
  
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">Surfalert</a>
        <ul class="nav pull-right">
          <% if user_logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "/logout" do %>
                    <i class="icon-off"></i> Sign Out
                  <% end %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to "Signup", new_user_path %>
            </li>
            <li>
              <%= link_to "Login", "/login" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    
    <%= notice_msg(flash[:notice]) if flash[:notice] %>
    <%= alert_msg(flash[:alert]) if flash[:alert] %>
  
    <%= yield %>

    <hr>
    <footer>
      <p>
        &copy; 2012 &middot; Surfalert
      </p>
    </footer>

  </div>

<%= yield :javascript %>
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/login/index.html.erb
<h1>Log in</h1>  
  
<%= form_tag "/login" do %>  
  <% unless flash[:notice].blank? %>
    <h3><%= flash[:notice] %></h3>
  <% end %>
  <div class="field">  
    <%= label_tag :email %>  
    <%= text_field_tag :email, params[:email] %>  
  </div>  
  <div class="field">  
    <%= label_tag :password %>  
    <%= password_field_tag :password %>  
  </div>  
  <div class="actions"><%= submit_tag "Log in" %></div>  
<% end %>  

app/views/surf_preferences/_form.html.erb
<%= form_for @surf_preference do |f| %>
  <% unless flash[:notice].blank? %>
    <h3><%= flash[:notice] %></h3>
  <% end %>
  <% if @surf_preference.errors.any? %>
    <div>
      <h3><%= pluralize(@surf_preference.errors.count, "error") %> was found:</h3>

      <ul>
      <% @surf_preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <%= f.label :min_size %>:
    <%= f.text_field :min_size, :placeholder => "In feet" %>
    <%= f.label :max_size %>:
    <%= f.text_field :max_size, :placeholder => "In feet" %>
    <%= f.label :min_shape %>:
    <%= select_tag "surf_preference[min_shape]", shape_selector_options(@surf_preference.min_shape).html_safe %>
    <%= f.label :spot_id %>:
    <%= select_tag "surf_preference[spot_id]", spot_selector_options(@surf_preference.spot_id).html_safe %>
    <%= f.label :start_time %>:
    <%= f.time_select :start_time, :class => "time" %>
    <%= f.label :end_time %>:
    <%= f.time_select :end_time, :class => "time" %>
 
  </fieldset>
  <button type="submit">Save</button>
<% end %>

app/views/surf_preferences/edit.html.erb
<%= form_for @surf_preference do |f| %>
  <% unless flash[:notice].blank? %>
    <h3><%= flash[:notice] %></h3>
  <% end %>
  <% if @surf_preference.errors.any? %>
    <div>
      <h3><%= pluralize(@surf_preference.errors.count, "error") %> was found:</h3>

      <ul>
      <% @surf_preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <%= f.label :max_size %>:
    <%= f.text_field :max_size, :placeholder => "In feet" %>
    <%= f.label :min_size %>:
    <%= f.text_field :min_size, :placeholder => "In feet" %>
    <%= f.label :min_shape %>:
    <%= select_tag "surf_preference[min_shape]", shape_selector_options(@surf_preference.min_shape).html_safe %>
    <%= f.label :spot_id %>:
    <%= select_tag "surf_preference[spot_id]", spot_selector_options(@surf_preference.spot_id).html_safe %>
  </fieldset>
  <button type="submit">Save</button>
<% end %>

app/views/surf_preferences/index.html.erb
<h1>Surf preferences</h1>

<ul>
  <% @surf_preferences.each do |surf_preference| %>
    <li>
      <%= link_to edit_surf_preference_path(surf_preference) do %>
        <%= surf_preference.min_size%>-<%= surf_preference.max_size %>ft, 
        <%= SurfPreference::SPOTS[surf_preference.spot_id] %>
      <% end %>
      &middot;
      <%= link_to "delete", surf_preference_path(surf_preference), :method => :delete, :confirm => "Are you sure?" %>
    </li>
  <% end %>
</ul>

<%= link_to "create new", new_surf_preference_path %>

app/views/surf_preferences/new.html.erb
<h1>New Preference</h1>

<%= render :partial => "form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% unless flash[:notice].blank? %>
    <h3><%= flash[:notice] %></h3>
  <% end %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_no %>
    <%= f.telephone_field :phone_no %>
  </div>
   <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>